# Generated by Django 5.0.2 on 2024-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_type', models.CharField(max_length=25)),
                ('join_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('books_borrowed', models.IntegerField()),
                ('max_books', models.IntegerField()),
                ('overdue_fees', models.IntegerField()),
            ],
        ),
    ]
